11 
    de.renew.gui.CPNDrawing 351 
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3763 "FillColor" "Color" 192 192 192 255 26 980 831 377 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3764 "FillColor" "Color" 192 192 192 255 26 459 262 493 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3765 "FillColor" "Color" 192 192 192 255 26 76 830 375 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3766 "FrameColor" "Color" 0 0 0 255 933 516 499 583 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3767 1298 1130 798 367 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3768 2211 505 322 646 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 1 "FigureWithID" "Int" 3769 1200 196 1068 231 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3770 "FillColor" "Color" 192 192 192 255 1839 685 277 268 8 8  
        CH.ifa.draw.figures.RoundRectangleFigure "attributes" "attributes" 2 "FigureWithID" "Int" 3771 "FillColor" "Color" 192 192 192 255 322 461 533 490 8 8  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3772 "FillColor" "Color" 112 219 147 255 430 176 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3773 2 1141 276 1269 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3869 "FillColor" "Color" 112 219 147 255 1121 266 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3774 "FillColor" "Color" 255 255 255 255 1269 268 24 16 NULL    REF 16 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3775 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1216 287 "team:new teamwork" "SansSerif" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -7 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3776 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 436 179 "[]" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3777 "FillColor" "Color" 255 255 255 255 2329 670 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3778 2 2342 558 2339 671 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3779 "FillColor" "Color" 255 255 255 255 2331 542 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 23   REF 27 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3780 2 2344 286 2343 542 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3793 "FillColor" "Color" 255 199 158 255 2334 266 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 27   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3781 "FillColor" "Color" 255 255 255 255 2326 803 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3782 "FillColor" "Color" 255 255 0 255 2496 966 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3783 2 2348 1065 2498 981 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3784 "FillColor" "Color" 255 255 255 255 2324 1064 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector REF 35   REF 39 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3785 2 2337 819 2336 932 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 34  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3786 "FillColor" "Color" 255 255 255 255 2326 931 20 20 NULL    REF 45 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3787 2 2336 951 2336 1064 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 45  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3788 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2315 602 "[aip,prb]" "SansSerif" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3789 2 2339 690 2338 803 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 34   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3790 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2313 739 "[aip,prb]" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3791 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2311 868 "[aip,prb]" "SansSerif" 0 12 0 REF 41 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3792 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2311 1000 "[aip,prb]" "SansSerif" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 32 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3794 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2491 951 "game" "SansSerif" 1 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator 2 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3795 2 1860 1238 1707 1148 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3815 "FillColor" "Color" 255 255 255 255 1858 1232 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3796 "FillColor" "Color" 255 255 255 255 1683 1134 24 16 NULL    REF 74 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3797 2 2336 1080 2336 1231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3798 "FillColor" "Color" 112 219 147 255 2326 1230 20 20 NULL    REF 79 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3799 2 1683 1148 1531 1238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 74  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3800 "FillColor" "Color" 255 255 255 255 1512 1232 20 20 NULL    REF 84 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3801 "FillColor" "Color" 255 255 255 255 1683 1196 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3802 2 1859 1241 1707 1206 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 85   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3803 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1589 1186 "payoff" "SansSerif" 0 12 0 REF 80 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3804 "FillColor" "Color" 255 255 255 255 1683 1321 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3805 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1649 1340 "guard(!A & !B);\npayoff=1+3;" "SansSerif" 0 12 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator -4 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3806 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1770 1216 "[A,B]" "SansSerif" 0 12 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3807 2 1860 1246 1707 1322 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 93   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3808 2 1683 1206 1532 1241 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 85  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3809 2 1683 1322 1531 1246 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 93  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3810 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1589 1216 "payoff" "SansSerif" 0 12 0 REF 104 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3811 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1589 1277 "payoff" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3812 2 2327 1240 2054 1241 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 79  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3813 "FillColor" "Color" 255 255 255 255 2030 1234 24 16 NULL    REF 122 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3814 2 2030 1242 1878 1242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 122  
            CH.ifa.draw.figures.ChopEllipseConnector REF 72   REF 72 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3816 2 1513 1242 1361 1242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 84  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3817 "FillColor" "Color" 255 255 255 255 1337 1234 24 16 NULL    REF 131 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3818 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1413 1227 "payoff1;\npayoff2;" "SansSerif" 0 12 0 REF 127 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3819 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1656 1156 "guard(A&B);\npayoff=3+1;" "SansSerif" 0 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator -1 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3820 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1653 1212 "guard((A&!B) );\npayoff=0+0;" "SansSerif" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 0 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3821 "FillColor" "Color" 255 255 255 255 2139 268 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3822 2 1951 276 2139 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3864 "FillColor" "Color" 255 255 255 255 1909 266 42 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 141   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3823 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2031 269 "team" "SansSerif" 0 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3824 2 2163 276 2335 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 141  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3825 "FillColor" "Color" 255 255 255 255 429 486 91 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3826 "FillColor" "Color" 255 255 255 255 539 601 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3827 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 488 617 ":readWeight(dp,x,y,z)" "SansSerif" 0 12 0 REF 155 
            CH.ifa.draw.standard.OffsetLocator -1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3828 2 1926 362 1688 806 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3845 "FillColor" "Color" 255 255 255 255 1919 346 24 16 NULL   
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3829 "FillColor" "Color" 112 219 147 255 1633 805 93 34 NULL    REF 164 
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3830 "FillColor" "Color" 255 255 255 255 "ArrowMode" "Int" 3 1121 957 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3831 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1784 577 "[dp,idx]" "SansSerif" 0 12 0 REF 159 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3832 "FillColor" "Color" 255 255 255 255 1965 813 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3833 3 1980 832 1999 870 1979 909 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 169  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3834 "FillColor" "Color" 255 255 255 255 1963 909 24 16 NULL    REF 174 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3835 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1940 925 ":incDecCnt()" "SansSerif" 0 12 0 REF 174 
            CH.ifa.draw.standard.OffsetLocator -1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3836 3 1971 832 1945 874 1969 909 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 169  
            CH.ifa.draw.standard.ChopBoxConnector REF 174   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3837 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1922 864 "dc" "SansSerif" 0 12 0 REF 178 
            CH.ifa.draw.standard.OffsetLocator -29 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3838 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2005 869 "dc+1" "SansSerif" 0 12 0 REF 170 
            CH.ifa.draw.standard.OffsetLocator 32 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3839 3 1979 815 1998 776 1979 738 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 169  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3840 "FillColor" "Color" 255 255 255 255 1963 722 24 16 NULL    REF 192 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3841 3 1971 815 1952 781 1971 738 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 169  
            CH.ifa.draw.standard.ChopBoxConnector REF 192   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3842 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1925 770 "dc" "SansSerif" 0 12 0 REF 193 
            CH.ifa.draw.standard.OffsetLocator -29 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3843 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2006 775 "dc-1" "SansSerif" 0 12 0 REF 188 
            CH.ifa.draw.standard.OffsetLocator 32 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3844 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1934 688 ":decDecCnt();\nguard(dc>0);" "SansSerif" 0 12 0 REF 192 
            CH.ifa.draw.standard.OffsetLocator -2 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 162 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3846 2 1649 834 1320 962 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 164  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3847 "FillColor" "Color" 255 255 255 255 1296 959 24 16 NULL    REF 210 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3848 2 1141 967 1296 967 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 165  
            CH.ifa.draw.standard.ChopBoxConnector REF 210   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3849 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1469 891 "[dp,i]" "SansSerif" 0 12 0 REF 206 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3850 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1200 960 "payoff" "SansSerif" 0 12 0 REF 211 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3851 2 1919 357 1822 391 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 162  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3852 "FillColor" "Color" 255 255 0 255 1802 383 20 20 NULL    REF 226 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3853 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1847 367 "[dp,idx]" "SansSerif" 0 12 0 REF 222 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3854 2 1131 958 1131 766 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 165  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3855 "FillColor" "Color" 255 255 255 255 1119 750 24 16 NULL    REF 234 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3856 "FillColor" "Color" 255 255 255 255 1870 815 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3857 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1846 831 ":setDecCnt()" "SansSerif" 0 12 0 REF 235 
            CH.ifa.draw.standard.OffsetLocator -1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3858 2 1894 823 1966 823 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 235  
            CH.ifa.draw.figures.ChopEllipseConnector REF 169   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3859 2 1985 823 2067 823 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 169  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3860 "FillColor" "Color" 255 255 255 255 2067 815 24 16 NULL    REF 247 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3861 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2022 816 "0" "SansSerif" 0 12 0 REF 243 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3862 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1825 390 "decision" "SansSerif" 1 12 0 REF 226 
            CH.ifa.draw.standard.OffsetLocator 39 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3863 2 1293 275 1493 273 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3873 "FillColor" "Color" 255 255 255 255 1492 263 20 20 NULL    REF 145 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3865 2 440 196 440 231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3866 "FillColor" "Color" 112 219 147 255 428 231 24 16 NULL    REF 263 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3867 2 441 247 474 487 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector REF 154   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 3868 "LineStyle" "String" "10" 3 428 241 136 295 114 490 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4017 "FillColor" "Color" 112 219 147 255 103 489 20 20 NULL REF 14    REF 14 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3870 2 430 247 346 320 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3871 "FillColor" "Color" 112 219 147 255 328 315 20 20 NULL    REF 277 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3872 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 385 276 "n" "SansSerif" 0 12 0 REF 273 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 258 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3874 "FillColor" "Color" 255 255 255 255 1490 353 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3875 3 1510 353 1547 318 1509 280 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 281  
            CH.ifa.draw.figures.ChopEllipseConnector REF 258   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3876 3 1495 280 1449 319 1491 353 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 258  
            CH.ifa.draw.standard.ChopBoxConnector REF 281   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3877 2 1512 273 1712 275 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 258  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3878 "FillColor" "Color" 255 255 255 255 1712 268 24 16 NULL    REF 294 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3879 2 1736 276 1910 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 294  
            CH.ifa.draw.figures.ChopEllipseConnector REF 145   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3880 "FillColor" "Color" 255 255 255 255 438 720 91 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3881 "FillColor" "Color" 255 255 255 255 388 597 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3882 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 336 613 ":writeWeight(dp,x,y,z)" "SansSerif" 0 12 0 REF 300 
            CH.ifa.draw.standard.OffsetLocator -1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3883 2 546 617 489 721 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 155  
            CH.ifa.draw.figures.ChopEllipseConnector REF 299   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3884 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 506 651 "[dp,x,y,z]" "SansSerif" 0 12 0 REF 304 
            CH.ifa.draw.standard.OffsetLocator 17 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3885 "FillColor" "Color" 112 219 147 255 327 356 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3886 2 338 335 338 356 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 277  
            CH.ifa.draw.standard.ChopBoxConnector REF 311   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3887 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1588 267 "[team,0]" "SansSerif" 0 12 0 REF 290 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3888 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1432 371 "guard(n>0);\nthis:readWeight(dp,x,y,z);\nteam:setWeight(dp,x,y,z);\n\n" "SansSerif" 0 12 0 REF 281 
            CH.ifa.draw.standard.OffsetLocator 4 47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3889 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1524 309 "[team,n-1]" "SansSerif" 0 12 0 REF 282 
            CH.ifa.draw.standard.OffsetLocator 27 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3890 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1428 310 "[team,n]" "SansSerif" 0 12 0 REF 286 
            CH.ifa.draw.standard.OffsetLocator -20 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3891 2 1337 1241 1141 1239 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 131  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3940 "FillColor" "Color" 112 219 147 255 "ArrowMode" "Int" 3 1121 1229 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3892 2 1930 346 1930 286 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 162  
            CH.ifa.draw.figures.ChopEllipseConnector REF 145   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3893 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1916 309 "team" "SansSerif" 0 12 0 REF 332 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3894 2 1131 750 1131 664 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 234  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3895 "FillColor" "Color" 255 255 255 255 1121 644 20 20 NULL    REF 344 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3896 "FillColor" "Color" 255 255 255 255 1013 646 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3897 3 1037 650 1075 639 1122 652 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 345  
            CH.ifa.draw.figures.ChopEllipseConnector REF 344   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3898 3 1122 657 1073 669 1037 657 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 344  
            CH.ifa.draw.standard.ChopBoxConnector REF 345   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3899 2 1131 645 1131 558 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 344  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3900 "FillColor" "Color" 255 255 255 255 1119 542 24 16 NULL    REF 358 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3901 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1127 594 "0" "SansSerif" 0 12 0 REF 354 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3902 2 1139 750 1218 682 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 234  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3903 "FillColor" "Color" 255 255 0 255 1214 665 20 20 NULL    REF 366 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3904 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1128 700 "n" "SansSerif" 0 12 0 REF 340 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3905 2 1131 542 1131 286 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 358  
            CH.ifa.draw.figures.ChopEllipseConnector REF 14   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3906 2 405 597 468 506 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 300  
            CH.ifa.draw.figures.ChopEllipseConnector REF 154   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3907 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 408 544 "[dp,x,y,z]" "SansSerif" 0 12 0 REF 374 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3908 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 489 461 "weights of DP" "SansSerif" 1 19 0 REF 154 
            CH.ifa.draw.standard.OffsetLocator 83 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3909 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1118 866 "payoff" "SansSerif" 0 12 0 REF 230 
            CH.ifa.draw.standard.OffsetLocator 5 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3910 2 481 506 545 601 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 154  
            CH.ifa.draw.standard.ChopBoxConnector REF 155   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3911 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 485 546 "[dp,x,y,z]" "SansSerif" 0 12 0 REF 387 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3912 2 478 721 405 613 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 299  
            CH.ifa.draw.standard.ChopBoxConnector REF 300   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3913 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 413 660 "[dp,x,y,z]" "SansSerif" 0 12 0 REF 394 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3914 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1809 269 "team" "SansSerif" 0 12 0 REF 295 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3915 2 2155 284 2213 390 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 141  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3916 "FillColor" "Color" 255 255 0 255 2207 388 20 20 NULL    REF 408 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3917 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2289 269 "prb" "SansSerif" 0 12 0 REF 150 
            CH.ifa.draw.standard.OffsetLocator 50 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3918 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2334 406 "prb" "SansSerif" 0 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3919 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 511 700 "weights (in use)" "SansSerif" 1 19 0 REF 299 
            CH.ifa.draw.standard.OffsetLocator 105 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3920 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 291 376 ":getNoOfDP(n);\n" "SansSerif" 0 12 0 REF 311 
            CH.ifa.draw.standard.OffsetLocator -5 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3921 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 941 669 "guard(n>0);\nthis:writeWeight(dp,x,y,z);\n" "SansSerif" 0 12 0 REF 345 
            CH.ifa.draw.standard.OffsetLocator -9 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3922 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1034 943 "reward:\ngame payoff" "SansSerif" 1 12 0 REF 165 
            CH.ifa.draw.standard.OffsetLocator -58 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3923 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1287 941 "update" "SansSerif" 1 12 0 REF 210 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3924 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1762 1180 "[A,B]" "SansSerif" 0 12 0 REF 69 
            CH.ifa.draw.standard.OffsetLocator -8 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3925 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1767 1278 "[A,B]" "SansSerif" 0 12 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator -3 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3926 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1993 799 "decision cnt" "SansSerif" 1 12 0 REF 169 
            CH.ifa.draw.standard.OffsetLocator 55 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3927 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1923 816 "0" "SansSerif" 0 12 0 REF 239 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3928 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2041 831 ":delDecCnt()" "SansSerif" 0 12 0 REF 247 
            CH.ifa.draw.standard.OffsetLocator -3 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3929 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1948 339 "store decision" "SansSerif" 1 12 0 REF 162 
            CH.ifa.draw.standard.OffsetLocator 61 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3930 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1692 248 "start team" "SansSerif" 1 12 0 REF 294 
            CH.ifa.draw.standard.OffsetLocator 0 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3931 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2360 535 "start aip" "SansSerif" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 43 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3932 "TextAlignment" "Int" 1 "FillColor" "Color" 192 192 192 255 2362 554 "aip:new aipsim" "SansSerif" 0 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator 62 11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3933 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2353 788 "start game" "SansSerif" 1 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 48 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3934 "TextAlignment" "Int" 1 "FillColor" "Color" 192 192 192 255 2358 809 "aip:startWFN(A,B,C,D);\nprb = [A,B,C,D];\n" "SansSerif" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 84 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3935 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2111 252 "stop team" "SansSerif" 1 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator -9 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3936 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2072 289 "team:getAIPconstraints(prb);\nprb = [A,B,C,D];" "SansSerif" 0 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator 3 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3937 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1468 1265 "payoff" "SansSerif" 1 12 0 REF 84 
            CH.ifa.draw.standard.OffsetLocator -34 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3938 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2134 1229 "[aip,\nprb,\n[[\"a\",A],[\"b\",B],[\"c\",C],[\"d\",D]]\n];" "SansSerif" 0 12 0 REF 118 
            CH.ifa.draw.standard.OffsetLocator 24 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3939 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1944 1206 "[A,B];\n[C,D];" "SansSerif" 0 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 6 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 331 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3941 2 1131 1230 1131 1080 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 331  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3942 "FillColor" "Color" 255 255 255 255 1119 1064 24 16 NULL    REF 482 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3943 2 1131 1064 1131 977 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 482  
            CH.ifa.draw.figures.ChopEllipseConnector REF 165   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3944 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1113 1013 "payoff" "SansSerif" 0 12 0 REF 483 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3945 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1113 1148 "payoff" "SansSerif" 0 12 0 REF 478 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3946 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1028 750 "stop uppdate" "SansSerif" 1 12 0 REF 234 
            CH.ifa.draw.standard.OffsetLocator -62 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3947 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1035 1066 "start update" "SansSerif" 1 12 0 REF 482 
            CH.ifa.draw.standard.OffsetLocator -58 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3948 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2356 1054 "end game" "SansSerif" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 50 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3949 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1680 290 "this:setDecCnt();\nteam:start();" "SansSerif" 0 12 0 REF 294 
            CH.ifa.draw.standard.OffsetLocator 3 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3950 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1916 244 "team" "SansSerif" 1 12 0 REF 145 
            CH.ifa.draw.standard.OffsetLocator 1 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3951 "TextAlignment" "Int" 2 "FillColor" "Color" 255 199 158 255 1955 355 "team:store(dp,idx);\nthis:incDecCnt();" "SansSerif" 0 12 0 REF 162 
            CH.ifa.draw.standard.OffsetLocator 80 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3952 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 319 338 "n" "SansSerif" 0 12 0 REF 312 
            CH.ifa.draw.standard.OffsetLocator -16 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3953 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1061 615 "n-1" "SansSerif" 0 12 0 REF 346 
            CH.ifa.draw.standard.OffsetLocator -7 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3954 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1092 668 "n" "SansSerif" 0 12 0 REF 350 
            CH.ifa.draw.standard.OffsetLocator 16 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3955 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1369 267 "[team,n]" "SansSerif" 0 12 0 REF 254 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3956 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 1759 154 "team formation: coordinate" "SansSerif" 0 36 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3957 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1618 830 "decisions" "SansSerif" 1 36 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator 26 29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3958 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 1797 1082 "observe reward" "SansSerif" 0 36 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3959 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2340 225 "coordination\nartefact" "SansSerif" 1 24 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 74 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3960 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1023 770 "this:delDecCnt();\nthis:getNoOfDP(n);\n" "SansSerif" 0 12 0 REF 234 
            CH.ifa.draw.standard.OffsetLocator -55 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3961 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 2352 458 "play game" "SansSerif" 0 36 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3962 "TextAlignment" "Int" 1 "FillColor" "Color" 192 192 192 255 2342 1083 "aip:endWFN(A,B,C,D);" "SansSerif" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 68 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3963 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2439 939 "[aip,\nprb,\n[[\"a\",A],\n[\"b\",B],\n[\"c\",C],\n[\"d\",D]]\n];" "SansSerif" 0 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 37 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3964 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2279 1157 "[aip,\nprb,\n[[\"a\",A],[\"b\",B],[\"c\",C],[\"d\",D]]\n];" "SansSerif" 0 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 23 32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3965 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 2181 354 "team" "SansSerif" 0 12 0 REF 404 
            CH.ifa.draw.standard.OffsetLocator 11 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3966 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 911 1254 "social welfare:\ncumulated game payoff" "SansSerif" 1 24 0 REF 331 
            CH.ifa.draw.standard.OffsetLocator -74 45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3967 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2341 1232 "game aip, \nactions taken" "SansSerif" 1 24 0 REF 79 
            CH.ifa.draw.standard.OffsetLocator 88 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3968 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1151 544 "this:incTime()" "SansSerif" 0 12 0 REF 358 
            CH.ifa.draw.standard.OffsetLocator 58 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3969 "FillColor" "Color" 112 219 147 255 150 228 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3970 2 428 238 170 238 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector REF 556   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3971 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 297 231 "t" "SansSerif" 0 12 0 REF 557 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3972 "FillColor" "Color" 112 219 147 255 50 230 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3973 3 74 244 108 263 152 242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 564  
            CH.ifa.draw.figures.ChopEllipseConnector REF 556   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3974 3 152 234 109 212 74 231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 556  
            CH.ifa.draw.standard.ChopBoxConnector REF 564   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3975 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 103 268 "t+1" "SansSerif" 0 12 0 REF 565 
            CH.ifa.draw.standard.OffsetLocator 1 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3976 "FillColor" "Color" 112 219 147 255 148 183 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3977 2 160 199 160 229 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 576  
            CH.ifa.draw.figures.ChopEllipseConnector REF 556   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3978 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 151 207 "t" "SansSerif" 0 12 0 REF 577 
            CH.ifa.draw.standard.OffsetLocator -7 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3979 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 118 166 ":getTime(t);\n" "SansSerif" 0 12 0 REF 576 
            CH.ifa.draw.standard.OffsetLocator -9 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3980 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 286 303 "noOfDP" "SansSerif" 1 12 0 REF 277 
            CH.ifa.draw.standard.OffsetLocator -28 -15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3981 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1160 709 "payoff" "SansSerif" 0 12 0 REF 362 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3982 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1213 304 "guard(t<RM);\nthis:getNoOfDP(n);\nthis:getTime(t);\nthis:getRoundMax(RM);" "SansSerif" 0 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator -2 58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3983 "FillColor" "Color" 112 219 147 255 309 159 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3984 2 428 232 328 174 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector REF 595   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3985 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 370 196 "rm" "SansSerif" 0 12 0 REF 596 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3986 "FillColor" "Color" 112 219 147 255 307 119 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3987 2 319 135 319 160 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 603  
            CH.ifa.draw.figures.ChopEllipseConnector REF 595   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3988 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 301 140 "rm" "SansSerif" 0 12 0 REF 604 
            CH.ifa.draw.standard.OffsetLocator -10 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3989 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 256 102 ":getRoundMax(rm);" "SansSerif" 0 12 0 REF 603 
            CH.ifa.draw.standard.OffsetLocator -8 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3990 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 523 372 "//Lists denote probabilities for high-vs-low probs.\n// First weight = all high prob. for Coop\n// Second weight = all low " "SansSerif" 0 12 0 NULL NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3991 "FillColor" "Color" 255 255 255 255 1683 1258 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3992 2 1859 1243 1707 1264 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 72  
            CH.ifa.draw.standard.ChopBoxConnector REF 614   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3993 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1770 1246 "[A,B]" "SansSerif" 0 12 0 REF 615 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3994 2 1683 1264 1532 1243 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 614  
            CH.ifa.draw.figures.ChopEllipseConnector REF 84   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3995 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1589 1246 "payoff" "SansSerif" 0 12 0 REF 622 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 3996 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1655 1274 "guard((!A&B));\npayoff=0+0;" "SansSerif" 0 12 0 REF 614 
            CH.ifa.draw.standard.OffsetLocator 0 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3997 2 1865 1424 1713 1395 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4008 "FillColor" "Color" 255 255 255 255 1864 1415 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3998 "FillColor" "Color" 255 255 255 255 1689 1385 24 16 NULL    REF 637 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 3999 2 1689 1395 1538 1424 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 637  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4000 "FillColor" "Color" 255 255 255 255 1518 1415 20 20 NULL    REF 642 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4001 "FillColor" "Color" 255 255 255 255 1689 1444 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4002 2 1865 1427 1713 1450 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 635  
            CH.ifa.draw.standard.ChopBoxConnector REF 643   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4003 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1581 1402 "payoff" "SansSerif" 0 12 0 REF 638 
            CH.ifa.draw.standard.OffsetLocator -14 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4004 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1776 1431 "[A,B]" "SansSerif" 0 12 0 REF 644 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4005 2 1689 1450 1538 1427 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 643  
            CH.ifa.draw.figures.ChopEllipseConnector REF 642   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4006 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1581 1431 "payoff" "SansSerif" 0 12 0 REF 654 
            CH.ifa.draw.standard.OffsetLocator -14 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4007 2 2034 1250 1881 1419 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 122  
            CH.ifa.draw.figures.ChopEllipseConnector REF 635   REF 635 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4009 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1628 1405 "guard((A&B) | ((!A)&(!B)));\npayoff=0+0;" "SansSerif" 0 12 0 REF 637 
            CH.ifa.draw.standard.OffsetLocator -1 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4010 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1633 1460 "guard( (A&!B) | (!A&B) );\npayoff=2+2;" "SansSerif" 0 12 0 REF 643 
            CH.ifa.draw.standard.OffsetLocator 0 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4011 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1768 1396 "[A,B]" "SansSerif" 0 12 0 REF 632 
            CH.ifa.draw.standard.OffsetLocator -8 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4012 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1474 1448 "payoff" "SansSerif" 1 12 0 REF 642 
            CH.ifa.draw.standard.OffsetLocator -34 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4013 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1947 1306 "[A,D];" "SansSerif" 0 12 0 REF 661 
            CH.ifa.draw.standard.OffsetLocator 6 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4014 2 1522 1419 1356 1250 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 642  
            CH.ifa.draw.standard.ChopBoxConnector REF 131   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4015 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1417 1327 "payoff3" "SansSerif" 0 12 0 REF 680 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4016 "FillColor" "Color" 255 255 255 255 577 142 24 16 NULL  REF 272 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4018 "FillColor" "Color" 255 255 255 255 102 545 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4019 2 113 509 113 545 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 272  
            CH.ifa.draw.standard.ChopBoxConnector REF 688   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4020 2 113 561 112 619 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 688  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4021 "FillColor" "Color" 255 255 255 255 102 618 20 20 NULL    REF 697 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4022 "FillColor" "Color" 255 255 255 255 97 708 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4023 3 114 708 134 677 116 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 698  
            CH.ifa.draw.figures.ChopEllipseConnector REF 697   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4024 3 108 637 89 671 105 708 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 697  
            CH.ifa.draw.standard.ChopBoxConnector REF 698   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4025 "FillColor" "Color" 255 255 255 255 181 621 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4026 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 140 665 "n-1" "SansSerif" 0 12 0 REF 699 
            CH.ifa.draw.standard.OffsetLocator 27 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4027 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 109 583 "n" "SansSerif" 0 12 0 REF 693 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4028 2 122 628 181 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 697  
            CH.ifa.draw.standard.ChopBoxConnector REF 707   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4029 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 147 621 "0" "SansSerif" 0 12 0 REF 714 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4030 2 205 629 238 629 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 707  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4031 "FillColor" "Color" 255 255 0 255 237 619 20 20 NULL    REF 725 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4032 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 54 464 "start of\nround" "SansSerif" 1 12 0 REF 272 
            CH.ifa.draw.standard.OffsetLocator -36 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4033 "FillColor" "Color" 112 219 147 255 224 192 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4034 2 428 236 244 204 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector REF 729   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4035 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 331 213 "st" "SansSerif" 0 12 0 REF 730 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4036 "FillColor" "Color" 112 219 147 255 222 100 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4037 2 234 116 234 193 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 737  
            CH.ifa.draw.figures.ChopEllipseConnector REF 729   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4038 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 222 147 "st" "SansSerif" 0 12 0 REF 738 
            CH.ifa.draw.standard.OffsetLocator -7 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4039 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 173 83 ":getSwitchTime(st)\n" "SansSerif" 0 12 0 REF 737 
            CH.ifa.draw.standard.OffsetLocator -9 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4040 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 489 80 ":getPayoffWeights(0.1,0.9,0.0);\nthis:getTime(t);\nthis:getSwitchTime(st);\nguard(t<st);" "SansSerif" 0 12 0 REF 687 
            CH.ifa.draw.standard.OffsetLocator -10 -40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4041 "FillColor" "Color" 255 255 255 255 766 141 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4042 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 678 79 ":getPayoffWeights(0.5,0.5,0.0);\nthis:getTime(t);\nthis:getSwitchTime(st);\nguard(t>=st);" "SansSerif" 0 12 0 REF 750 
            CH.ifa.draw.standard.OffsetLocator -10 -40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4043 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 36 247 ":incTime();\n" "SansSerif" 0 12 0 REF 564 
            CH.ifa.draw.standard.OffsetLocator 4 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4044 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 111 195 "t" "SansSerif" 0 12 0 REF 569 
            CH.ifa.draw.standard.OffsetLocator 0 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4045 3 428 243 232 309 161 398 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4046 "FillColor" "Color" 192 192 192 255 145 395 20 20 NULL    REF 764 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4047 "FillColor" "Color" 112 219 147 255 242 399 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4048 2 242 406 165 405 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 765  
            CH.ifa.draw.figures.ChopEllipseConnector REF 764   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4049 2 157 415 191 621 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 764  
            CH.ifa.draw.standard.ChopBoxConnector REF 707   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4050 "FillColor" "Color" 255 255 255 255 641 491 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4051 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 595 507 ":logWeight(dp,x,y,z)" "SansSerif" 0 12 0 REF 773 
            CH.ifa.draw.standard.OffsetLocator -1 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4052 2 519 497 641 498 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 154  
            CH.ifa.draw.standard.ChopBoxConnector REF 773   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4053 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 552 490 "[dp,x,y,z]" "SansSerif" 0 12 0 REF 777 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4054 2 121 715 214 714 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 698  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4055 "FillColor" "Color" 255 255 255 255 213 704 59 20 NULL    REF 788 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4056 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 139 707 "[dp,x,y,z]" "SansSerif" 0 12 0 REF 784 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4057 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 190 684 "final weights" "SansSerif" 1 14 0 REF 788 
            CH.ifa.draw.standard.OffsetLocator -5 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4058 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 166 636 "action writer.flush();\naction writer.close()" "SansSerif" 0 12 0 REF 707 
            CH.ifa.draw.standard.OffsetLocator 30 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4059 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 576 630 "this:getTime(t);\nthis:getWriter(writer);\naction writer.println(s);\nthis:format(t,dp,x,y,z,s);\n" "SansSerif" 0 10 0 REF 155 
            CH.ifa.draw.standard.OffsetLocator 83 53 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4060 "FillColor" "Color" 255 255 255 255 651 754 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4061 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 34 727 "guard(n>0);\nthis:logWeight(dp,x,y,z);\nthis:getTime(t);\naction System.out.println(s);\nthis:format(t,dp,x,y,z,s);\nthis:getWriter(writer);\naction writer.println(s);" "SansSerif" 0 12 0 REF 698 
            CH.ifa.draw.standard.OffsetLocator 4 63 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4062 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 214 601 "end of sim" "SansSerif" 1 12 0 REF 725 
            CH.ifa.draw.standard.OffsetLocator 0 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4063 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1075 211 "start of\n round" "SansSerif" 1 24 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator -10 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4064 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 75 545 "end" "SansSerif" 1 12 0 REF 688 
            CH.ifa.draw.standard.OffsetLocator -28 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4065 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 601 771 ":format(t,dp,x,y,z,s);\ns = t\n+\"; \" \n+ dp\n+\"; \" \n+ (int)(100*x)\n+\"; \" \n+ (int)(100*y)\n+\"; \" \n+ (int)(100*z)\n+\"; \" \n" "SansSerif" 0 12 0 REF 801 
            CH.ifa.draw.standard.OffsetLocator -2 99 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4066 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1190 1219 "a*payoff1\n+b*payoff2\n+c*payoff3" "SansSerif" 0 12 0 REF 327 
            CH.ifa.draw.standard.OffsetLocator -15 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4067 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1312 1206 "this:getPayoffWeights(a,b,c)" "SansSerif" 0 12 0 REF 131 
            CH.ifa.draw.standard.OffsetLocator 42 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4068 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 1822 1186 "Battle-of-Sexes" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4069 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 1816 1381 "Anti-Coordination" "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4070 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 58 30 "init simulation" "SansSerif" 0 36 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4071 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 399 280 "[\"abcd\",0,3,4];\n[\"ab\",100,0,0];\n[\"cd\",100,0,0];\n\n[{\"a\",\"b\",\"c\",\"d\"},100,1,0];\n[{\"a\",\"b\"},50,50,0];\n[{\"c\",\"d\"},50,50,0];\n[{\"a\"},100,1,0];\n[{\"b\"},100,1,0];\n[{\"c\"},100,1,0];\n[{\"d\"},100,1,0];\n" "SansSerif" 0 12 0 REF 264 
            CH.ifa.draw.standard.OffsetLocator 14 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4072 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 180 333 "writer" "SansSerif" 0 12 0 REF 760 
            CH.ifa.draw.standard.OffsetLocator -98 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4073 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 186 411 "writer" "SansSerif" 0 12 0 REF 766 
            CH.ifa.draw.standard.OffsetLocator -1 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4074 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 158 580 "writer" "SansSerif" 0 12 0 REF 769 
            CH.ifa.draw.standard.OffsetLocator 0 69 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4075 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 78 664 "n" "SansSerif" 0 12 0 REF 703 
            CH.ifa.draw.standard.OffsetLocator -17 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4076 "TextAlignment" "Int" 1 "FillColor" "Color" 192 192 192 255 130 494 "guard(t >= RM);\nthis:getNoOfDP(n);\nthis:getTime(t);\nthis:getRoundMax(RM);\n" "SansSerif" 0 12 0 REF 688 
            CH.ifa.draw.standard.OffsetLocator 82 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4077 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 233 416 ":getWriter(writer)\n" "SansSerif" 0 12 0 REF 765 
            CH.ifa.draw.standard.OffsetLocator 27 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4078 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 525 294 "//Strings denotes probabilities alternative splits.\n//First weight = stop splitting" "SansSerif" 0 12 0 NULL NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4079 "FillColor" "Color" 255 255 255 255 145 1057 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4080 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 41 1079 "i=0;\nthis:getAlpha(a);\nx2=a*x+(1-a)*payoff;\ny2=y;\nz2=z;\n:getUpdates(dp,i,payoff,x,y,z,x2,y2,z2);\n" "SansSerif" 0 12 0 REF 848 
            CH.ifa.draw.standard.OffsetLocator 0 66 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4081 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 122 1039 "calc update" "SansSerif" 1 12 0 REF 848 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4082 "FillColor" "Color" 255 255 255 255 392 1057 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4083 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 288 1079 "i=1;\nthis:getAlpha(a);\nx2=x;\ny2=a*y+(1-a)*payoff;\nz2=z;\n:getUpdates(dp,i,payoff,x,y,z,x2,y2,z2);\n" "SansSerif" 0 12 0 REF 855 
            CH.ifa.draw.standard.OffsetLocator 0 66 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4084 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 369 1039 "calc update" "SansSerif" 1 12 0 REF 855 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4085 "FillColor" "Color" 255 255 255 255 640 1057 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4086 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 536 1079 "i=2;\nthis:getAlpha(a);\nx2=x;\ny2=y;\nz2=a*z+(1-a)*payoff;\n:getUpdates(dp,i,payoff,x,y,z,x2,y2,z2);\n" "SansSerif" 0 12 0 REF 862 
            CH.ifa.draw.standard.OffsetLocator 0 66 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4087 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 617 1039 "calc update" "SansSerif" 1 12 0 REF 862 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 3730 "FillColor" "Color" 255 255 255 255 132 1225 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4088 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 96 1207 "calc dampening" "SansSerif" 1 12 0 REF 869 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4089 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 78 1246 ":getDamp(dp,i,damp);;\ndamp=1;\n" "SansSerif" 0 12 0 REF 869 
            CH.ifa.draw.standard.OffsetLocator 1 35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4090 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 233 1219 "// Dampening is used for terminating splitting\n// dampening should depend on the size of the set\n// larger sets should observe a weaker signal" "SansSerif" 0 12 0 NULL NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4091 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 455 209 "manual;\nn=10; t=0;rm=100;st=50;a=0.9;\nwriter = new java.io.PrintWriter(\"iteratedgamelog\"\n+java.lang.System.currentTimeMillis()+\".csv\", \"UTF-8\");" "SansSerif" 0 12 0 REF 263 
            CH.ifa.draw.standard.OffsetLocator 173 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4092 "TextAlignment" "Int" 0 "FillColor" "Color" 255 199 158 255 1152 470 "feedback: update adapt-or" "SansSerif" 0 36 0 NULL NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4093 "FillColor" "Color" 112 219 147 255 387 170 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4094 2 434 231 403 188 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 263  
            CH.ifa.draw.figures.ChopEllipseConnector REF 881   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4095 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 415 202 "a" "SansSerif" 0 12 0 REF 882 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4096 "FillColor" "Color" 112 219 147 255 387 98 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4097 2 398 114 397 171 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 889  
            CH.ifa.draw.figures.ChopEllipseConnector REF 881   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4098 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 384 135 "a" "SansSerif" 0 12 0 REF 890 
            CH.ifa.draw.standard.OffsetLocator -10 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4099 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 354 81 ":getAlpha(a);" "SansSerif" 0 12 0 REF 889 
            CH.ifa.draw.standard.OffsetLocator -8 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4100 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 360 155 "alpha" "SansSerif" 1 12 0 REF 881 
            CH.ifa.draw.standard.OffsetLocator -20 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4101 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 268 180 "max round" "SansSerif" 1 12 0 REF 595 
            CH.ifa.draw.standard.OffsetLocator -18 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4102 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 226 214 "switch time" "SansSerif" 1 12 0 REF 729 
            CH.ifa.draw.standard.OffsetLocator 28 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4103 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 150 248 "round" "SansSerif" 1 12 0 REF 556 
            CH.ifa.draw.standard.OffsetLocator 8 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4104 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1139 1052 "this:getTime(t);\nthis:getWriter(writer);\naction writer.println(t+\";\"+\"payoff ; \" + payoff);\n" "SansSerif" 0 12 0 REF 482 
            CH.ifa.draw.standard.OffsetLocator 143 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4105 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1179 985 "this:decDecCnt();\nthis:updateWeights(dp,x,y,z,x2,y2,z2);\nthis:getUpdates(dp,i,payoff,x,y,z,x2,y2,z2);\n" "SansSerif" 0 12 0 REF 210 
            CH.ifa.draw.standard.OffsetLocator -3 48 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4106 3 490 740 524 789 488 840 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 299  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 4108 "FillColor" "Color" 255 255 255 255 471 840 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 4107 3 474 840 422 790 474 740 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 921  
            CH.ifa.draw.figures.ChopEllipseConnector REF 299   REF 921 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4109 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 368 784 "[dp,x2,y2,z2]" "SansSerif" 0 12 0 REF 922 
            CH.ifa.draw.standard.OffsetLocator -40 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4110 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 509 780 "[dp,x,y,z]" "SansSerif" 0 12 0 REF 917 
            CH.ifa.draw.standard.OffsetLocator 31 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4111 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 386 858 ":updateWeights(dp,x,y,z,x2,y2,z2);\n" "SansSerif" 0 12 0 REF 921 
            CH.ifa.draw.standard.OffsetLocator 5 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 4112 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 500 839 "update" "SansSerif" 1 12 0 REF 921 
            CH.ifa.draw.standard.OffsetLocator 38 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  NULL  